!oamie_pos_x_sub    = $3140 ; tile x offset, sub.
!oamie_pos_x_lo     = $3141 ;                lo.
!oamie_pos_x_hi     = $3142 ;                hi.
!oamie_pos_y_sub    = $3143 ;      y offset, sub.
!oamie_pos_y_lo     = $3144 ;                lo.
!oamie_pos_y_hi     = $3145 ;                hi.
!oamie_num          = $3146 ;      number.
!oamie_props        = $3147 ;      yxppccct properties.
!oamie_size9        = $3148 ;      extra properties. format : 000000sb
                            ;      s = size. (8px is clear, 16px if set)
                            ;      b = pos x 9th bit.
!oamie_buffer       = $3149 ; maxtile buffer. ($00-$30 -> 0-3)